SpiLoader optimized: support to continue loading extensions if one of…
esastack/esa-commons pull request #29
Opened 2021-05-21 10:07 UTC by scofildwang

… them failed to be instantiated.

2021-05-21 10:19 UTC, scofildwang commented
@alalag1

2021-05-21 10:37 UTC, alalag1 requested changes

2021-05-21 10:37 UTC, alalag1 commented on commons/src/test/java/esa/commons/spi/extensionloader/AllTypeGetExtensionFunctionTest.java
> +    public void continueIfErrTest() {
plz declare test method  as package-private level

2021-05-21 10:37 UTC, alalag1 commented on commons/src/test/java/esa/commons/spi/extensionloader/AllTypeGetExtensionFunctionTest.java
> +        assertNull(list);
maybe it would be better to use `assertThrows(Exception.class, () -> { xxxx })`

2021-05-24 08:17 UTC, alalag1 commented
@scofildwang  thanks a lot!

2021-05-24 08:17 UTC, merged